[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
crowdfund = "5R3oAoFaFuKgVeYG1qwjhRRuZWNFiq9tXf56e5yDymrr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
skip_confirmation = false # This is important! It enables retries.
commitment = "confirmed"
preflightCommitment = "processed"
number_of_retries = 20 # Increase as needed

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
