[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
sol_donate = "3jTdr2xdnCvzPEehRwoNarvhxh2m5W7YJwyJBk4ts8ng"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "dev.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
